const constructionRoles = [
  { id: 1, name: "Architect" },
  { id: 2, name: "Civil Engineer" },
  { id: 3, name: "Structural Engineer" },
  { id: 4, name: "General Contractor" },
  { id: 5, name: "Project Manager" },
  { id: 6, name: "Site Supervisor" },
  { id: 7, name: "Quantity Surveyor" },
  { id: 8, name: "Building Surveyor" },
  { id: 9, name: "Building Inspector" },
  { id: 10, name: "Land Surveyor" },
  { id: 11, name: "Landscape Architect" },
  { id: 12, name: "Geotechnical Engineer" },
  { id: 13, name: "Environmental Engineer" },
  { id: 14, name: "Health and Safety Officer" },
  { id: 15, name: "Interior Designer" },
  { id: 16, name: "Draftsman" },
  { id: 17, name: "Plumber" },
  { id: 18, name: "Electrician" },
  { id: 19, name: "HVAC Technician" },
  { id: 20, name: "Carpenter" },
  { id: 21, name: "Mason" },
  { id: 22, name: "Painter" },
  { id: 23, name: "Roofer" },
  { id: 24, name: "Tiler" },
  { id: 25, name: "Glazier" },
  { id: 26, name: "Concrete Laborer" },
  { id: 27, name: "Metalworker" },
  { id: 28, name: "Drywaller" },
  { id: 29, name: "Insulation Contractor" },
  { id: 30, name: "Pest Control Specialist" },
  { id: 31, name: "Excavator Operator" },
  { id: 32, name: "Heavy Equipment Operator" },
  { id: 33, name: "Site Cleanup Crew" },
  { id: 34, name: "Security Personnel" },
  { id: 35, name: "Project Coordinator" },
  { id: 36, name: "Procurement Specialist" },
  { id: 37, name: "Logistics Manager" },
  { id: 38, name: "Administrative Support" },
  { id: 39, name: "Legal Advisor" },
  { id: 40, name: "Finance Manager" },
  { id: 41, name: "Construction Foreman" },
  { id: 42, name: "Scaffold Erector" },
  { id: 43, name: "Steel Fixer" },
  { id: 44, name: "Floor Layer" },
  { id: 45, name: "Ceiling Installer" },
  { id: 46, name: "Cabinet Maker" },
  { id: 47, name: "Bricklayer" },
  { id: 48, name: "Crane Operator" },
  { id: 49, name: "Survey Technician" },
  { id: 50, name: "Solar Panel Installer" },
  {id:52,name:"Bank Loan"},
  { id: 51, name: "Miscellaneous" },
];

export const constructionRolesFilterSearch = [
  { id: 1, name: "Architect" },
  { id: 2, name: "Civil Engineer" },
  { id: 3, name: "Structural Engineer" },
  { id: 4, name: "General Contractor" },
  { id: 5, name: "Project Manager" },
  { id: 6, name: "Site Supervisor" },
  { id: 7, name: "Quantity Surveyor" },
  { id: 8, name: "Building Surveyor" },
  { id: 9, name: "Building Inspector" },
  { id: 10, name: "Land Surveyor" },
  { id: 11, name: "Landscape Architect" },
  { id: 12, name: "Geotechnical Engineer" },
  { id: 13, name: "Environmental Engineer" },
  { id: 14, name: "Health and Safety Officer" },
  { id: 15, name: "Interior Designer" },
  { id: 16, name: "Draftsman" },
  { id: 17, name: "Plumber" },
  { id: 18, name: "Electrician" },
  { id: 19, name: "HVAC Technician" },
  { id: 20, name: "Carpenter" },
  { id: 21, name: "Mason" },
  { id: 22, name: "Painter" },
  { id: 23, name: "Roofer" },
  { id: 24, name: "Tiler" },
  { id: 25, name: "Glazier" },
  { id: 26, name: "Concrete Laborer" },
  { id: 27, name: "Metalworker" },
  { id: 28, name: "Drywaller" },
  { id: 29, name: "Insulation Contractor" },
  { id: 30, name: "Pest Control Specialist" },
  { id: 31, name: "Excavator Operator" },
  { id: 32, name: "Heavy Equipment Operator" },
  { id: 33, name: "Site Cleanup Crew" },
  { id: 34, name: "Security Personnel" },
  { id: 35, name: "Project Coordinator" },
  { id: 36, name: "Procurement Specialist" },
  { id: 37, name: "Logistics Manager" },
  { id: 38, name: "Administrative Support" },
  { id: 39, name: "Legal Advisor" },
  { id: 40, name: "Finance Manager" },
  { id: 41, name: "Construction Foreman" },
  { id: 42, name: "Scaffold Erector" },
  { id: 43, name: "Steel Fixer" },
  { id: 44, name: "Floor Layer" },
  { id: 45, name: "Ceiling Installer" },
  { id: 46, name: "Cabinet Maker" },
  { id: 47, name: "Bricklayer" },
  { id: 48, name: "Crane Operator" },
  { id: 49, name: "Survey Technician" },
  { id: 50, name: "Solar Panel Installer" },
   {id:52,name:"Bank Loan"},
  { id: 51, name: "Miscellaneous" },
  // { id: -1, name: "" },
];

export default constructionRoles;
