const paymentTypes = [
  { id: 1, name: "Cash" },
  { id: 2, name: "Credit Card" },
  { id: 3, name: "Debit Card" },
  { id: 4, name: "Bank Transfer" },
  { id: 5, name: "Cheque" },
  { id: 6, name: "Mobile Payment" },
  { id: 7, name: "Cryptocurrency" },
  { id: 8, name: "PayPal" },
  { id: 9, name: "Wire Transfer" },
  { id: 10, name: "Direct Debit" },
  { id: 11, name: "Money Order" },
  { id: 12, name: "Prepaid Card" },
  { id: 13, name: "Electronic Funds Transfer (EFT)" },
  { id: 14, name: "Google Pay" },
  { id: 15, name: "Apple Pay" },
  { id: 16, name: "Amazon Pay" },
  { id: 17, name: "UPI" },
  { id: 18, name: "Net Banking" },
  { id: 19, name: "Gift Card" },
  { id: 20, name: "Coupon" },
  { id: 21, name: "Cashier's Check" },
  { id: 22, name: "Traveler's Check" },
  { id: 23, name: "Pay Order" },
  { id: 24, name: "Demand Draft" },
  { id: 25, name: "Western Union" },
  { id: 26, name: "Venmo" },
  { id: 27, name: "Square Cash" },
  { id: 28, name: "Zelle" },
  { id: 29, name: "ACH Transfer" },
  { id: 30, name: "Personal Check" },
  { id: 31, name: "Postal Order" },
  { id: 32, name: "Bill Pay" },
  { id: 33, name: "Auto Pay" },
  { id: 34, name: "Contactless Payment" },
  { id: 35, name: "Escrow" },
  { id: 36, name: "Payroll Card" },
  { id: 37, name: "Virtual Card" },
  { id: 38, name: "RTGS" },
  { id: 39, name: "NEFT" },
  { id: 40, name: "SWIFT Transfer" },
  { id: 41, name: "Electronic Check" },
  { id: 42, name: "Paytm" },
  { id: 43, name: "PhonePe" },
  { id: 44, name: "Unified Payments Interface (UPI)" },
  { id: 45, name: "NetBanking" },
  { id: 46, name: "Bharat QR" },
  { id: 47, name: "Rupay" },
  { id: 48, name: "MobiKwik" },
  { id: 49, name: "FreeCharge" },
  { id: 50, name: "Sodexo" },
];

export  const paymentTypesFilterSearch = [
  { id: 1, name: "Cash" },
  { id: 2, name: "Credit Card" },
  { id: 3, name: "Debit Card" },
  { id: 4, name: "Bank Transfer" },
  { id: 5, name: "Cheque" },
  { id: 6, name: "Mobile Payment" },
  { id: 7, name: "Cryptocurrency" },
  { id: 8, name: "PayPal" },
  { id: 9, name: "Wire Transfer" },
  { id: 10, name: "Direct Debit" },
  { id: 11, name: "Money Order" },
  { id: 12, name: "Prepaid Card" },
  { id: 13, name: "Electronic Funds Transfer (EFT)" },
  { id: 14, name: "Google Pay" },
  { id: 15, name: "Apple Pay" },
  { id: 16, name: "Amazon Pay" },
  { id: 17, name: "UPI" },
  { id: 18, name: "Net Banking" },
  { id: 19, name: "Gift Card" },
  { id: 20, name: "Coupon" },
  { id: 21, name: "Cashier's Check" },
  { id: 22, name: "Traveler's Check" },
  { id: 23, name: "Pay Order" },
  { id: 24, name: "Demand Draft" },
  { id: 25, name: "Western Union" },
  { id: 26, name: "Venmo" },
  { id: 27, name: "Square Cash" },
  { id: 28, name: "Zelle" },
  { id: 29, name: "ACH Transfer" },
  { id: 30, name: "Personal Check" },
  { id: 31, name: "Postal Order" },
  { id: 32, name: "Bill Pay" },
  { id: 33, name: "Auto Pay" },
  { id: 34, name: "Contactless Payment" },
  { id: 35, name: "Escrow" },
  { id: 36, name: "Payroll Card" },
  { id: 37, name: "Virtual Card" },
  { id: 38, name: "RTGS" },
  { id: 39, name: "NEFT" },
  { id: 40, name: "SWIFT Transfer" },
  { id: 41, name: "Electronic Check" },
  { id: 42, name: "Paytm" },
  { id: 43, name: "PhonePe" },
  { id: 44, name: "Unified Payments Interface (UPI)" },
  { id: 45, name: "NetBanking" },
  { id: 46, name: "Bharat QR" },
  { id: 47, name: "Rupay" },
  { id: 48, name: "MobiKwik" },
  { id: 49, name: "FreeCharge" },
  { id: 50, name: "Sodexo" },
  // {id:-1,name:""}
];

export default paymentTypes;
